### PR TITLE
hopefully fixing font-size problem with ul

### LINKED ISSUE #68: On website, bullet points have larger font size than paragraphs
At least on my computer with different javascript blocked, the font size of the paragraph elements is smaller than the bullet points.

I think this is the case on one of other websites, too.

### PR DESCRIPTION
**Pull request by bast**
@rkdarst can you please test locally wither this fixes #68?

### CODE REVIEW

**Comment by rkdarst** [comment]
My local build looks like it works!  Tested two computers, I can't be sure there's not something still wrong, but I will merge and see...

Good job figuring this out, to me it's magic.

**Comment by rkdarst** [comment]
Refreshing the main site (in the tab where it previously didn't work) shows that now it *does* work...

**Comment by bast** [comment]
Glad it works now. It also shows that I don't really know CSS and was only testing on forgiving browsers :-)

**Comment by bast** [comment]
You mentioned there was some other website with the same problem (likely since I often copy-paste this)?

**Pull request merged**
