### PR TITLE
communities/finland: Expand zoom link

### PR DESCRIPTION
**Pull request by rkdarst**
- Each month I get annoyed at copying and pasting the components of
  the URL (since I don't want to bounce it through the browser).
- Language is effectively always English.  Even if not, if anyone
  doesn't speak Finnish, it is English, and if everyone does Finnish
  obviously they can do whatever they like.  I think this makes it
  more welcoming to people joining, they don't have to ask "what does
  mostly mean?"
- Review: general check, @rantahar

### CODE REVIEW

**Comment by rantahar** [comment]
* Expanding the link is a good idea. If it is a recurring problem for you, it is probably a problem for someone else.
* Did you make intent to make a change related to language? I agree with your comment. We could clarify the language is essentially always English.

**Comment by rkdarst** [comment]
Oops... yes, there was a language change.  I guess I was trying to be clever and do it separately and forgot... added now.

**Comment by rkdarst** [comment]
Should I merge this?

**Comment by rantahar** [comment]
Looks good to me

**Pull request merged**
