### PR TITLE
link to the proposal incubator

### PR DESCRIPTION
**Pull request by bast**
relates to #92

### CODE REVIEW

**Review by rkdarst — APPROVED** [review]
I approve, should we wait for others to be positive to the idea before accepting?

**Comment by bast** [comment]
Sounds good. Let's wait a bit.

**Comment by wleoncio** [comment]
Looks good, though if my [idea from another post](https://github.com/nordic-rse/nordic-rse.github.io/issues/92#issuecomment-718407218) gets accepted, the link would need to be changed.

**Comment by rantahar** [comment]
Nothing against this. I would also like to invite anyone interested in developing the agenda to the biweekly meetings

**Pull request merged**
