### PR TITLE
In the community map, allow lists of places for groups (and individuals)

### PR DESCRIPTION
**Pull request by rantahar**

### CODE REVIEW

**Comment by rantahar** [comment]
This draws each institute in all places listed (and same for individuals, if they list multiple places). The downside is that it adds multiple pins where no individual RSE is marked close by.

**Comment by rantahar** [comment]
The preview does not seem to work. I think it still loads the javascript from the main version.

**Comment by lucaferranti** [comment]
You need to tweak manually the link of the preview when you look at something which is not the homepage, see this issue: https://github.com/nordic-rse/nordic-rse.github.io/issues/453.

Correct link should be: https://nordic-rse.org/previews/PR455/communities/map/

**Comment by rantahar** [comment]
@lucaferranti, that still loads the wrong javascript.

**Comment by rantahar** [comment]
Made a quick fix in the map data by using only one location. This is easy to revert

**Comment by lucaferranti** [comment]
yeah, I noticed that. Not sure why :thinking:

**Comment by lucaferranti** [comment]
I think if you ran that locally and works locally, we can assume it's just github setup and merge this

**Comment by rantahar** [comment]
It works, but I'm not sure we want to do this. It's more a suggested fix.

**Pull request merged**
