### PR TITLE
Statutes of association

### PR DESCRIPTION
**Pull request by rantahar**
I started working here on a proposal to start an association. It contains a short description on why we would want to do this and a draft of the statutes of the association.

The draft is in English even though the final statutes must be in Swedish or Finnish. I will write a proper translation (probably in Swedish) once I know they will not change much.

The statutes are minimal and standard. I would like input of sections 1 and 2, the name and the purpose of the association.

Also, would this belong on the Nordic RSE page in the first place? We need to post it somewhere, but perhaps the association should have a separate site?

### CODE REVIEW

**Comment by annefou** [comment]
Maybe we should make sure that it will allow us to participate as a Nordic RSE organization; for instance in the perspective of the RSE starter pack and "council" of national RSEs.

I think here what we are aiming at is to reproduce what is called The Software Sustainability Institute (which is great!).

**Comment by rkdarst** [comment]
Anne, why would this now allow us to participate?  Because the bylaws are too broad?

I think it's standard for the stated purpose to be as broad as possible, so as to not be limited later.  I think it would be appropriate to be even broader than what is here, including "the advancement of scientific computing and education in scientific computing" in addition.  (Once I read how companies are usually incorporated for "<what they do> and other business" so that they can't be constricted.)

Of course a related question is "what do we want the scope to be" and how it might relate to CodeRefinery.

**Comment by annefou** [comment]
because we would be too narrow and not inclusive enough.

First my opinion (but I know we have orthogonal views when it comes to computing/HPC) is that the name "Nordic Research Software and Computing Association" is ambiguous (according to wikipedia computing includes development of both hardware and software; is it really what we want?) and does not broaden the initial intent. 
Second, it will be even more ambigous if we start to have different purposes and sub-groups. This comment is related to 
> An association allows different kinds of memberships. We may decide to
> * have all member so the Nordic RSE group be members
> * that only active members in the three projects should be members
> * and may additionally include supporting members with a different membership fee.

Again, my feeling is that rather than broading it, it will create another "elite" club and in a few years (analyzing the background, gender, etc of our members), we will wonder how to become more inclusive. My opinion is that we should be inclusive by design.

**Comment by rkdarst** [comment]
Comments on rules:

* Associations act in English: https://www.prh.fi/en/yhdistysrekisteri/act.html

* Mandatory provisions in rules: https://www.prh.fi/en/yhdistysrekisteri/for_registered_associations/rules/instructions_on_the_provisions_of_association_rules.html

  * Name must end in Ry
  * List domicile (Helsinki?)
  * Perhaps we need to work on the purpose some more: https://www.prh.fi/fi/yhdistysrekisteri/rekisteroidylle_yhdistykselle/saantojen_muutosilmoitus/mallit_yhdistyksen_tarkoitukseksi_ja_toimintamuodoiksi.html

* Chairperson of executive committee does not have to be a Finnish resident (this exception must be given by PRH, sec 35).  Exception costs 100€.     I propose we executive chairperson + majority of board members must be Nordics+Baltics.  https://www.prh.fi/en/yhdistysrekisteri/perustaminen/start-up_notification/the_chairperson_and_other_persons_entitled_to_sign_for_the_association/exemption_for_a_chairperson_living_abroad.html

I would have more comments but the overall purpose (plus if this will happen in finland, or even soon) should be decided first.

But if we have someone who would like to work on this, I guess there is limited to delay?

**Comment by susamerz** [comment]
Regarding the purpose: is it necessary to limit the purpose to academia? Say someone was a researcher doing software development, became a member, and then went on to do research for a company, would they then be excluded, just because they changed jobs?

**Comment by rkdarst** [comment]
I agree, we shouldn't exclude non-academic people, but also distinguish us from normal software development..  I guess "research" covers our spirit enough, there are researchers in companies, too.

Even if it is focused on academics, we should make sure that nothing excludes people in industry or that have moved there and want to still be in our network.

**Comment by rantahar** [comment]
Thanks for the comments.

@annefou, In the part you are referring to, I am musing on the the possible purpose of the organisation. The first option would be that it would only exist for the practical purpose of having a bank account (and therefore not be very inclusive at all). The other option would be an actual association that has a number of members and is as inclusive as possible. The rules are written for the second purpose, there is no mention of any restriction on membership.

However I'm not sure if you have a way to make them more inclusive in mind. I would be interested to talk about this.

I added the word "computing" to also include Nordic HPC, but the only reason for this (in my mind) is to reduce administration. If there is any practical reason to limit the association to software (and not hardware), that is easy to do.


@susamerz, I guess the main concerns that I have in mind come from academia, but I don't really see a reason to narrow the focus there. With the rules I wrote, anyone can be a member, so changing jobs would not affect that in any case.


@rkdarst, The part about the chairperson being a Finnish resident is a good catch I did not notice. It's not a huge extra cost, but a bit of an annoyance anyway.

Restricting the board to be residents of the Nordics+Baltics would make sense, but it would constrain us later if something weird happens. I guess that is a rather unlikely problem.

We definitely need to work on the purpose of the association first. Everything else should flow from that. My original idea was that this would simplify organising events, working with fees, sponsorships and such. But if we do this, it's worth doing it well and create an organisation that has a good long term structure.

**Comment by rantahar** [comment]
I have changed the first section to remove my musings and comments. I hope this will clarify the proposal.

When I have any more musings, I will just post them here.

**Comment by rkdarst** [comment]
oops, my other PR just also used association/ ...

**Comment by rantahar** [comment]
I noticed it and moved the file back, so that the statutes are in association/

**Comment by rkdarst** [comment]
To make things concrete here is my suggestion (not that it should be used but a full suggestion is better than comments):

:::
The name of the association is the Nordic Research Software Engineers Ry and it is domiciled in Helsinki, Finland

The purpose of the association is to support research software engineering and scientific computing.

The association fulfills its purpose by
    * maintaining a network of research software engineers and other similar specialists and representing that network to others
    * hosting events for members and the surrounding community
    * supporting training and professional development in related skills for members and the surrounding community
    * recognizing significant contributions to research software engineering and related fields
    * advocating for research software engineers and engineering
    * Other activities in the public interest promoting research software and scientific computing 

In order to support its activities, the association may accept and manage funds according to relevant permits and own property.
:::

I tried to think of more things that we might do, to make it explicit, while focusing on research software.  While also including "other activities" at the end, it tries to emphasise RSE in all other aspects.  I think being broad is important, especally since in the RSE leaders meeting there were threads about making sure the other technical specialists (HPC engineers, database experts, etc) are included.  The definition of a RSE and if it still means what it used to is another point but we should not exclude them from the start.

I would be happy if this could be made shorter.

The model purposes always made a specific note of accepting funds and managing assets so I added that.

**Comment by rkdarst** [comment]
btw, here are model rules: https://www.prh.fi/fi/yhdistysrekisteri/rekisteroidylle_yhdistykselle/saantojen_muutosilmoitus/saantomallit.html

and model purposes: https://www.prh.fi/fi/yhdistysrekisteri/rekisteroidylle_yhdistykselle/saantojen_muutosilmoitus/mallit_yhdistyksen_tarkoitukseksi_ja_toimintamuodoiksi.html

both in fi/sv only.

**Pull request closed without merging**
