### PR TITLE
conference/submissions: Draft submissions page

### PR DESCRIPTION
**Pull request by rkdarst**
- I've scouted our google docs for ideas, but didn't find a very good
  reference for what kind of wording people want.  So, I made it up.

### CODE REVIEW

**Comment by bast** [comment]
Thanks! I think this is a great start. Shall I merge and we go from there?

**Comment by rkdarst** [comment]
Make sure it's added to the navigation, then yes, if you think so.

**Comment by rkdarst** [comment]
Now added to nav, title "Submit an abstract" though I also thought about "Submit an event".

**Comment by bast** [comment]
Thank you!

**Pull request merged**
