### PR TITLE
add SSI as sponsor

### PR DESCRIPTION
**Pull request by samumantha**
~~- Is it sponsor or funder?~~
- Should the text say something more specific?
- Image may need some rescaling

### CODE REVIEW

**Comment by mtomasini** [comment]
I feel like "funder" is the currect term, but maybe at SSI they have a preference?

**Comment by samumantha** [comment]
I asked, but only got the logo guidelines for now. 

Should the logo be added also to registration page etc?

**Review by mtomasini — APPROVED** [review]
Looks good to me!

**Comment by mtomasini** [comment]
Ah damn me I just saw the changed file, not your last comment @samumantha. I think we can add a logo later if we find it necessary. For sure we will have to add it to all our presentations, etc.

**Pull request merged**
