### PR TITLE
make the page easier to read on web and in terminal

### PR DESCRIPTION
**Pull request by bast**

### CODE REVIEW

**Comment by lucaferranti** [comment]
there seems to be some issue with the table of content (not introduced by this PR, but this could be a good place to bring it up). If it is too much work, let us just open an issue about this and work it out later

image

**Review by lucaferranti — APPROVED** [review]

**Comment by bast** [comment]
But what is the issue with the TOC?

**Comment by lucaferranti** [comment]
The location is a little weird, isn't it? I would have placed it below the title and not next to it, but I guess that can be subjective

**Comment by bast** [comment]
I found it actually quite convenient there. I am merging but happy to accept changes.

**Pull request merged**
