### PR TITLE
Add basic info about september seminar

### PR DESCRIPTION
**Pull request by samumantha**
title maybe not right and content is missing
After title is confirmed by @bast, imo we can also fill more detailed content later. Maybe most important that the event gets on the webpage asap?

### CODE REVIEW

**Comment by lucaferranti** [comment]
Looks very good! A short abstract about the  talk might be good, but I guess that can be added later.

Looking forward to it

**Review by lucaferranti — APPROVED** [review]

**Comment by bast** [comment]
I am now traveling but will add abstract in a day or two. Thanks for preparing this!

**Comment by samumantha** [comment]
Great :)

**Comment by bast** [comment]
I will add abstract and resources in a bit but good to already have this merged. Thanks again!

**Pull request merged**
