### PR TITLE
Update biweekly meeting and join us page; add calendar

### LINKED ISSUE #218: Update biweekly meeting info and active public members
Update the biweekly meeting information and add a link to the public google calendar. Update the active public members.

### PR DESCRIPTION
**Pull request by PatricHolmvall**
Closes #218

### CODE REVIEW

**Comment by PatricHolmvall** [comment]
Let me know if you like the idea of putting the calendar on the "Events" page.

**Comment by bast** [comment]
Good idea to put it on the events page.

**Comment by PatricHolmvall** [comment]
Check out the HackMD to get an idea how it will look like on the website: https://hackmd.io/3QnRFT-5TOOXjzHtATJ_iA?view

**Review by bast — APPROVED** [review]

**Comment by PatricHolmvall** [comment]
Unless someone is in the process of reviewing, I think we can merge it.

**Comment by bast** [comment]
Merging ...

**Pull request merged**
