### PR TITLE
Switch to serving map data from githack CDN

### PR DESCRIPTION
**Pull request by frankier**
raw.githubusercontent.com can get throttled eventually

### CODE REVIEW

**Comment by bast** [comment]
Should it point to a branch instead of a hash?

**Comment by frankier** [comment]
So it should! I think I just pasted that from the form.

**Review by bast — APPROVED** [review]
I am honestly not sure which option is better. I don't think throttling is a risk for this project and for our size of traffic. githack looks like 3rd party. In another project I had the problem that I depended on https://rawgit.com/ which at some point stopped. But I trust your judgement if githack is better.

**Comment by rkdarst** [comment]
The githack main page says two options:
- production, no limits, but use a specific hash or tag because it is cached permanently
- development, can be throttled, reasonable to use a branch since updates are reflected soon

So, it seems the semantics aren't quite right for what we need?
Anyone know the rate limits of raw.githubusercontent.com?

**Comment by bast** [comment]
I use raw.githubusercontent.com quite a bit over the years and haven't experienced any throttling.

**Comment by bast** [comment]
I appreciate the change and good that I learned about a new service but maybe let's not change it yet since it works currently? OK if I close this? Also OK for me if this gets merged. We can always move back. I just want to have fewer long-lived PRs.

**Comment by frankier** [comment]
Yep I think this one was a false positive. Closing.

**Pull request closed without merging**
