### PR TITLE
_nordic-events/2020-12-01-get-together: Add Nov 30th

### PR DESCRIPTION
**Pull request by rkdarst**
- We discussed the possibility of keynotes Friday; add notice of them.
- Review: ensure this is still the plan.  Are 1-2.dec half days?
  Morning or afternoon?

### CODE REVIEW

**Comment by rantahar** [comment]
In the PC meeting we talked about having workshops and talks in the morning and more networking oriented things in the afternoon. Half days are not a bad idea, it might be easier for people to attend. In that case it should not be early in the morning, earliest 9 CET.

We also talked about an epilogue talk on the 3rd, but that one would overlap with another workshop.

**Review by annefou — APPROVED** [review]

**Comment by bast** [comment]
I am merging and we can refine later. I agree that we need to stay clear from Dec 3.

**Comment by rkdarst** [comment]
Updated, thanks for clarifying to me.

**Comment by bast** [comment]
Did I merge too early?

**Comment by rkdarst** [comment]
Yes, seems we had a race condition in merging.  New PR made (since
it's easy...) so check that.

**Pull request merged**
