### PR TITLE
Update unconference schedule and add 4th invited talk

### PR DESCRIPTION
**Pull request by PatricHolmvall**
Add 4th invited talk, and various updates in the schedule

### CODE REVIEW

**Comment by bast** [comment]
@annefou are you happy with the abstract? (we can always change later)

**Review by bast — APPROVED** [review]

**Comment by PatricHolmvall** [comment]
> @annefou are you happy with the abstract? (we can always change later)

@bast It is copy-pasted from Anne's GitHub issue, so hopefully that is OK for now(?).

**Review by samumantha — APPROVED** [review]
Looks good! Thanks for updating :)

**Comment by annefou** [comment]
yes. good enough (I still have no idea what to really show but I am sure we can find out something!). Thanks.

**Comment by samumantha** [comment]
Just noticed, Annes talk is also not yet in the longer teaser part on the unconference page

**Comment by samumantha** [comment]
Github collaborator newbee question: Would it here be ok to 'invade' Patrics suggestion and add another commit adding Annes talk to the page? 
It did not feel right to do that, therefor only a comment. 
Please let me know what you think should be the procedure here.  :) 
Is comment in the code maybe a good way for these kind of suggestions?

**Comment by bast** [comment]
I would not find it invasive to add a new commit. Comment suggestion is also good.

**Comment by PatricHolmvall** [comment]
@samumantha always feel free to add to any suggestions. I certainly do not feel that it is invasive.

**Comment by bast** [comment]
Samantha working on the modification? Should I? No pressure just to be clear who is now working on it.

**Comment by PatricHolmvall** [comment]
> Samantha working on the modification? Should I? No pressure just to be clear who is now working on it.

I was just thinking the same. Just saw that the SNIC email went out, advertising the Nordic-RSE unconference. Feels like it would be good to update the schedule. I'm pushing an amended commit, sorry if someone started already.

**Pull request merged**
