### PR TITLE
make unconference page more readable

### PR DESCRIPTION
**Pull request by bast**
- two important links are on top as buttons
- announcement texts moved to sub-page
- consent-type information for speakers moved to issue template
- overall less text to read

### CODE REVIEW

**Comment by bast** [comment]
Just a sec I will attach a screenshot to make it easier to review ...

**Comment by bast** [comment]
screenshot

**Comment by lucaferranti** [comment]
for the schedule, I suggest to use the `<summary>` and `<details>` tag, so that one can expand the abstract if they want

**Comment by lucaferranti** [comment]
inspiration:https://juliareach.github.io/juliareach-days-3/#Program

**Comment by bast** [comment]
Good idea but let's move that to a new issue that somebody can take?

**Comment by bast** [comment]
I am creating issue ...

**Comment by bast** [comment]
> I am creating issue ...

followed-up in #392

**Comment by lucaferranti** [comment]
> Good idea but let's move that to a new issue that somebody can take?

absolutely, I think this PR fullfills its purpose

**Review by lucaferranti — APPROVED** [review]

**Pull request merged**
