### PR TITLE
fix status english-finnish inconsitency

### LINKED ISSUE #400: inconsitency between English and Finnish statuses
The English one says the annual meeting is held between June -- September, the Finnish one says between August and October

### PR DESCRIPTION
**Pull request by lucaferranti**
fixes #400 , since technically the Finnish one is the official one, I updated the English one.

### CODE REVIEW

**Review by mtomasini — COMMENTED** [review]
There is also article 11. missing in the Finnish version! Why not add it with this commit?

**Comment by lucaferranti** [comment]
> There is also article 11. missing in the Finnish version!

@rantahar

**Review by lucaferranti — COMMENTED** [review]
- update board members
- clarify where to ask for fee wave

**Review by mtomasini — APPROVED** [review]
Looks good to me! Do you need to put other e-mail addresses for the board members, or yours and Jarno's are enough?

**Comment by lucaferranti** [comment]
> Do you need to put other e-mail addresses for the board members

I guess every one can add their email if they want to

**Pull request merged**
