### PR TITLE
add slides for one presentation

### PR DESCRIPTION
**Pull request by bast**
for review: unsure whether we want to host these on the website
repo (this repo) or in a separate repo?

### CODE REVIEW

**Comment by rkdarst** [comment]
What about in the meetups repository?  Or a separate meeting-specific repo for materials?

**Comment by bast** [comment]
What would be your preference? My slight preference is meetups repo.

**Comment by samumantha** [comment]
One more vote for meetups repo here. Or into the google drive and linked?

**Comment by bast** [comment]
We can also always change the location later if we also update the website but I like the idea of not pulling everything into the website repo history.

I will send a PR towards meetups and also update this one afterwards.

**Comment by bast** [comment]
But now I also rediscovered https://github.com/nordic-rse/nordic-rse-materials :man_shrugging:

**Comment by bast** [comment]
> But now I also rediscovered https://github.com/nordic-rse/nordic-rse-materials

But that one has a CC-BY license which could be misunderstood also for the slides. I will park it under meetups.

**Comment by bast** [comment]
Ready to go once https://github.com/nordic-rse/meetups/pull/17 is in.

**Pull request merged**
