### PR TITLE
add SORSE button

### PR DESCRIPTION
**Pull request by annefou**
Thought having access to SORSE from the navbar would be nice... Just a suggestion!

### CODE REVIEW

**Comment by wleoncio** [comment]
I agree with connecting the two websites, but the navbar looks like such a prominent place for this. Since the https://sorse.github.io/ homepage seems to be very focused on their events, maybe the link should be placed in https://nordic-rse.org/events/.

P.S.: Coincidentally, just before seeing this I was syncing their calendar to my Evolution client and wondered if Nordic-RSE also had a public iCal file. Just this week I noticed I still had the old Wednesday arrangement for the RSE bi-weekly meeting, which is something that would be avoided by having an official source (not to mention it could potentially increase participation).

**Review by wleoncio — COMMENTED** [review]
I agree with connecting the two websites, but the navbar looks like such a prominent place for this. Since the https://sorse.github.io/ homepage seems to be very focused on their events, maybe the link should be placed in https://nordic-rse.org/events/.

P.S.: Coincidentally, just before seeing this I was syncing their calendar to my Evolution client and wondered if Nordic-RSE also had a public iCal file. Just this week I noticed I still had the old Wednesday arrangement for the RSE bi-weekly meeting, which is something that would be avoided by having an official source (not to mention it could potentially increase participation).

**Comment by annefou** [comment]
Ok. events for me was related to Nordic-RSE events where SORSE does not really fit. I like the idea of having a calendar. We could then have Nordic-RSE events and other external events.

**Comment by bast** [comment]
Merging. Unsure what the conclusion was but we can follow-up with adjustments in separate PRs.

**Pull request merged**
