### PR TITLE
Update biweekly time

### PR DESCRIPTION
**Pull request by rantahar**
Review:
 - Anything else we need to say?
 - Spelling, links

### CODE REVIEW

**Comment by bast** [comment]
Text is good. My only concern is that I am not sure whether a week is even or odd.
This year it is easy since Jan 1 was a Monday but sometimes I get conflicting info from different calendars about week number. But let's start like this in 2024 and think about it more in 2025.

**Comment by lucaferranti** [comment]
could just write "every other week" and link to the calendar to check which one is when

**Review by mtomasini — APPROVED** [review]

**Comment by rantahar** [comment]
Then we need to update the calendar. But good idea.

**Comment by rantahar** [comment]
Actually, would it make more sense to direct people to the agenda? We can add the date there if we need a meeting.

**Comment by bast** [comment]
Still draft or ready to merge? Ready from my perspective.

**Review by mtomasini — APPROVED** [review]
Looks good to me. We will really have to remember to update the HackMD... ;)

**Comment by rantahar** [comment]
My idea is that if we need a meeting, we will update the HackMD before.

**Comment by rantahar** [comment]
Oh, I did not mean to make it a draft

**Pull request merged**
