### PR TITLE
make the schedule easier to read

### PR DESCRIPTION
**Pull request by bast**
... but maybe more difficult to write?

No talk/workshop titles yet, wanted to confirm first that the contributors have been informed.

### CODE REVIEW

**Comment by bast** [comment]
I will attach a screenshot ...

**Comment by bast** [comment]
schedule

**Review by wikfeldt — APPROVED** [review]
not that much more difficult to write, and it looks much better

**Comment by bast** [comment]
At least for me it visually helps. We can always change colors and stuff.

**Review by rkdarst — APPROVED** [review]
Looks good to me, html table isn't ideal but almost certainly better than any other option.  And it really needed this clarity to be added.

**Pull request merged**
