### PR TITLE
added icons to purple box

### PR DESCRIPTION
**Pull request by lucaferranti**
image

### CODE REVIEW

**Comment by samumantha** [comment]
Otherwise looks great <3

**Comment by lucaferranti** [comment]
I think the icons match the text size at the moment?

Putting them above the text might require a little more tweaking with paddings and sizes to make it nice and responsive, but it's definitely doable, I can give it a try later today.

**Comment by samumantha** [comment]
Hmm in the picture it looks to me like they are a tiny bit taller (visible mostly at success stories), but might also be such a small detail that does not really matter to people. Maybe I am looking at it wrong 🤔

**Comment by bast** [comment]
I will merge and then we can adjust still. It's definitely an improvement.

**Pull request merged**
