### PR TITLE
updated navbar

### PR DESCRIPTION
**Pull request by lucaferranti**
updted navbar based on today discussion

## TODO:
see my latest message below

### CODE REVIEW

**Comment by samumantha** [comment]
How would be the best way, if I want to continue working on this?

**Comment by lucaferranti** [comment]
sorry I didn't manage to push this as fast as hoped. I guess what remains to be done is to update the links in the navbar to the pages in the webpage and possibly create placeholders empty pages etc. Can you directly push to this branch?

**Comment by lucaferranti** [comment]
To facilitate collaboration, here the navbar of this PR as TODO list with missing links etc.

- ABOUT
  - [x] Governance (links to association folder)
  - [ ] Code of conduct (didn't find one)
  - [ ] Contact (where should it point)

- COMMUNITIES
  - [x] Members
  - [x] Local communities
  - [ ] Coffee break (points to the coffee break section which is under Finland page), maybe we should move the coffee break elsewhere and Finland should be a subsection in local communities page
  
- EVENTS
  - [x] Seminar Series
  - [x] Meeting (points to the events page, where the Biweekly meeting is first, not sure if it's optimal
  - [x] Past events, points to the past events section in the events page. There's a small CSS glitch, but otherwise it's fine
  - [x] Calendar, points to the calendar, so technically fine. Calendar is atm below past events, which probably is not optimal
  
- [x] Blog: points to the blog page
- [x] Resources: points to the "media" folder, not sure if it's right

- [ ] Join us, don't know where it should point out 

cc @samumantha @bast

**Comment by lucaferranti** [comment]
Proposal for the ABOUT section

- We keep governance pointing to the folder association
- We add a `## Code of Conduct` section there which has the CoC if short or a link to it if longer and the `COde of Conduct` in the navbar points to it accordingly
- We add to the `/association/_index.md` a `## Contact` which has contact information and navbar link points there

For Join us: can it point directly to the form?

**Comment by bast** [comment]
Working on it today to get these nice changes in ...

**Comment by lucaferranti** [comment]
do not hesitate to ping me if you need help!

**Comment by bast** [comment]
I will merge this and for the remaining work I will create placeholders and follow-up issues. Otherwise this sits here forever. Better 90% done and merged than 100% not merged.

**Pull request merged**
