### PR TITLE
Rename 2020-12-01-get-together to 2020-online-get-together

### PR DESCRIPTION
**Pull request by rkdarst**
- Uses this plugin, which is already enabled:
  https://github.com/jekyll/jekyll-redirect-from
- As discussed in zulipchat
- Review:
  - is the name what we want?
  - does this actually work?  (perhaps merge and then check...)

### CODE REVIEW

**Comment by rkdarst** [comment]
and local building does work, but we need to make sure it works on gh-pages

**Comment by bast** [comment]
Why /nordic-events/ and not simply /events/?

**Comment by rkdarst** [comment]
> Why /nordic-events/ and not simply /events/?

It's that way on website now, there is /events/ and /other-events/.  I didn't do it at least...

I would be +1 on /nordic-events to /events/

**Comment by bast** [comment]
Let's keep it simple and intuitive. Can I help with the renames?

**Comment by rkdarst** [comment]
I say merge this then rename.  Or delegate it to me...

**Comment by bast** [comment]
OK I will do the rename tonight after dinner.

**Comment by rkdarst** [comment]
Actually the reason probably is that https://nordic-rse.org/events/ is already taken by a non-collection.  Maybe, I'm not entirely sure how it works...

**Comment by bast** [comment]
I am sure this can be somehow solved. We should not let Jekyll impose URLs on us.

**Comment by rkdarst** [comment]
It works

**Comment by bast** [comment]
Awesome!

**Pull request merged**
