### PR TITLE
tentative timeline towards the conference; closes #43

### LINKED ISSUE #43: Publish tentative timeline and calls
Very early tentative draft (taken from PC meeting minutes):

Review - 15th September - 7th October 
Notification of acceptance of abstracts - 15th October
Open registrations - ?
Registration opens (probably more a question of OC, but still) - September?
Registration closes (probably more a question for OC, but still) - 31st October
Decision to postpone conference - 31st October
Conference opens - 1st December

Can be used as inspiration: https://nl-rse.org/2019/07/09/NL-RSE-2019.html

### PR DESCRIPTION
**Pull request by bast**
I have moved the "Call for talks and workshops opens" back to end of
July since we need to have the rest ready and we are a bit behind.

### CODE REVIEW

**Comment by rkdarst** [comment]
Do you think the covid-19 should be merged into this, and title adjusted to "important dates/covid-19" ?

**Comment by bast** [comment]
Good idea - I will merge these two and add to this PR.

**Comment by rkdarst** [comment]
One last suggestion: bold the important dates that most attendees need to know (basically the non-covid ones)?  It's now hard to scan down and see what is relevant to me...

**Comment by bast** [comment]
Merged to avoid conflicts.

**Comment by rkdarst** [comment]
at least on my screen, it's still quite hard to tell things apart.  Could the text itself also be bolded?

**Comment by bast** [comment]
> at least on my screen, it's still quite hard to tell things apart. Could the text itself also be bolded?

followed-up in #76

**Pull request merged**
